version: 0.0
os: linux
files:
  - source: /
    destination: /app
hooks:
  BeforeInstall:
    - location: scripts/removeExistingApp.sh
      timeout: 180
      runas: root
  AfterInstall:
    - location: scripts/setPermissions.sh
      timeout: 180
      runas: root      
