version: 0.2
            
phases:
  build:
    commands:
      - ls /var/lib/docker
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker run --rm -v $(pwd):/app composer/composer install
      - docker run --rm -v $(pwd):/app -w /app lucor/php7-cli php bin/install.php translations develop
      - docker run --rm -i -v $(pwd):/app -w /app digitallyseamless/nodejs-bower-grunt sh -c "npm install && bower install && grunt package"
artifacts:
  files:
    - public/**/*
    - application/**/*
    - vendor/**/*
    - database/**/*
    - appspec.yml
    - scripts/**/*
cache:
  paths:
    - /root/.composer/cache/**/*
    - /root/.npm/**/*
    - /root/.cache/bower/packages/**/*
    - /var/lib/docker/**/*.qcow2