version: 0.2
            
phases:
  install:
    commands:
      - chmod 755 bin/devinstall.sh
      - chmod 755 bin/gendocs.sh
  pre_build:
    commands:
      - bin/devinstall.sh
  post_build:
    commands:
      - zip -r package.zip public application vendor database
artifacts:
  files:
    - package.zip
cache:
  paths:
    - /root/.composer/cache/**/*
    - /root/.npm/**/*
    - /root/.cache/bower/packages/**/*