version: 0.2
            
phases:
  install:
    commands:
      - ls
      - sudo apt-get install git composer python-software-properties curl apache2 mysql-server-5.7 libapache2-mod-php7.0 php7.0-intl php7.0-mcrypt php7.0-bcmath php7.0-curl php7.0-gd php7.0-mysql php7.0-mbstring php7.0-zip -y
      - git --version
      - php --version
      - composer --version
      - apache2 -v
      - mysql --version
      - curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash -
      - apt-get install nodejs -y
      - npm -v
      - npm install -g bower
      - bower -v
      - npm install -g grunt-cli
      - grunt -V
  pre_build:
    commands:
      - bin/devinstall.sh
artifacts:
  files:
    - public/**/*
    - application/**/*
    - vendor/**/*
    - database/**/*