version: 0.2
            
phases:
  install:
    commands:
      - chmod 755 bin/devinstall.sh
      - chmod 755 bin/gendocs.sh
  pre_build:
    commands:
      - bin/devinstall.sh
artifacts:
  files:
    - public/**/*
    - application/**/*
    - vendor/**/*
    - database/**/*
    - appspec.yml
    - scripts/**/*
cache:
  paths:
    - /root/.composer/cache/**/*
    - /root/.npm/**/*
    - /root/.cache/bower/packages/**/*