version: 0.2
            
phases:
  install:
    commands:
      - apt-get install php-zip # Needed for composer
      - php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
      - php -r "if (hash_file('SHA384', 'composer-setup.php') === '544e09ee996cdf60ece3804abc52599c22b1f40f4323403c44d44fdfdd586475ca9813a858088ffbc1f233e9b180f061') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"
      - php composer-setup.php
      - php -r "unlink('composer-setup.php');"
      - composer --version
      - curl -sL https://deb.nodesource.com/setup_10.x | bash -
      - apt-get install nodejs -y
      - npm -v
      - npm install -g bower
      - bower -v
      - npm install -g grunt-cli
      - grunt -V
      - chmod 777 bin/devinstall.sh
      - chmod 777 bin/gendocs.sh
  pre_build:
    commands:
      - bin/devinstall.sh
artifacts:
  files:
    - public/**/*
    - application/**/*
    - vendor/**/*
    - database/**/*
cache:
  paths:
    - node_modules/**/*